### ISSUE TITLE
USER STORY: Stock tracking

### ISSUE THREAD

**Issue by spangen87** [spangen87/bls-digital#16]
As a **admin** I can **see and edit a stock levels of a product** so that **we don't sell products we don't have in stock**.

# Acceptance Criteria
* User can't buy product that is out of stock
* Admin can edit stock levels directly from the store
* User can see stock levels on product detail page

## Tasks
- [ ] Create logic for stock handling, must important to not sell products that is not in stock.
- [ ] Add page for view and edit stock levels for admin
- [ ] Render levels on product detail page
