### ISSUE TITLE
USER STORY: Send message

### ISSUE THREAD

**Issue by spangen87** [spangen87/bls-digital#3]
As a **user** I can **send a message to the store** so that **I can get answers to my questions**.

# Acceptance Criteria
* A contact form
*
*

## Tasks
- [ ] Add a contact page
- [ ] Add a contact form
- [ ] Add success and error messages
- [ ] Set up email
