### ISSUE TITLE
USER STORY: View my bag

### ISSUE THREAD

**Issue by spangen87** [spangen87/bls-digital#4]
As a **user** I can **view my bag** so that **I can see what I'm buying before going to the checkout**.

# Acceptance Criteria
* View shopping bag
* Edit the bag
* Delete products

## Tasks
- [x] Add quantity picker
- [x] Add button for removing product
- [x] View list of products with price, image and quantity
