### ISSUE TITLE
ADMIN STORY: Add, delete and edit products

### ISSUE THREAD

**Issue by spangen87** [spangen87/bls-digital#6]
As a **admin** I can **add, edit and delete a product** so that **I can manage the products easily**.

# Acceptance Criteria
* Add new product
* Edit a existing product
* Delete a product

## Tasks
- [ ] Add CRUD functionality to products
- [ ] Add links to product page
- [ ] Only available when logged in as admin of the store
